### ISSUE TITLE
Add team page

### ISSUE THREAD

**Issue by momack2** [FilecoinFoundationWeb/filecoin-foundation-site#4]
![image](https://user-images.githubusercontent.com/618519/94607368-abece380-0250-11eb-82b9-63bba41862fe.png)

**Comment by filecoincorgi** [comment]
The team page will launch as soon as we finalize our advisors and get ready to announce. @hugomrdias can we still have the page design setup but not fully "committed/hidden" for the time being?

**Comment by filecoincorgi** [comment]
@momack2 this has already been added it is just hidden https://github.com/FilecoinFoundationWeb/filecoin-foundation-site/blob/master/team.njk

**Comment by dud1337** [comment]
Given the redesign with Agency Undone and the state of `team.njk`, I suggest we wait this to be fixed with the new version of the website.

**Comment by orvn** [comment]
Thanks for flagging @dud1337!
