### ISSUE TITLE
please update favicon

### ISSUE THREAD

**Issue by gmoranxyz** [FilecoinFoundationWeb/filecoin-foundation-site#43]
New image attached. Thank you!

![Favicon](https://user-images.githubusercontent.com/22464426/138253353-ec2f823c-266d-4dda-8749-98fdf89764be.png)

**Comment by orvn** [comment]
It was actually changed to the inverted version of that ([visible here](https://fil.org/favicon/ms-icon-144x144.png)).

Not sure if that's what you saw when your created this ticket or if you were seeing the old site's favicon (It may require a cache clear on your end locally).

<img src="https://fil.org/favicon/ms-icon-144x144.png">

**Comment by gmoranxyz** [comment]
Hi @orvn ! I saw the updated one but I think the shape is too thin to work as a knockout at favicon scale. I did some visual tests to check the other colour should work better.

![image](https://user-images.githubusercontent.com/22464426/138386805-dfb67ece-0597-42ef-9d16-17890fc81d97.png)
