### ISSUE TITLE
Add all upcoming events

### ISSUE THREAD

**Issue by TimGuo7** [FilecoinFoundationWeb/filecoin-foundation-site#79]
Under the events page, when click all, can we have so many upcoming or planned events on this page?
that will be easier for community member to track all the events that is happening with Filecoin.
or have a sub-tab like **Upcoming Events.** 
<img width="991" alt="Screen Shot 2021-11-11 at 11 12 40 PM" src="https://user-images.githubusercontent.com/94029052/141322745-7bda6947-07c7-409d-b4a0-4e79718afe06.png">

**Comment by orvn** [comment]
@gmoranxyz, this is a pretty old ticket, but I think you added the most recent events a long while back yes? If so, can I close this?

**Comment by orvn** [comment]
New events and hackathons weren't displaying correctly due to a bug, this is now resolved

<img width="500" alt="ff-events-hackathons" src="https://user-images.githubusercontent.com/3689720/192796742-e21b4094-a897-4cbe-8c85-287c3e82d742.png">
